export const SET_PLAYLIST = 'SET_PLAYLIST';
export const SET_PLAYCURRENTINDEX = 'SET_PLAYCURRENTINDEX';
export const SET_LYRIC = 'SET_LYRIC';
export const SET_ISPAUSE = 'SET_ISPAUSE';
export const SET_CURRENTTIME = 'SET_CURRENTTIME';
export const SET_CURRENTLYRICINDEX = 'SET_CURRENTLYRICINDEX';
